import os
import getpass

root = os.path.dirname(os.path.dirname(__file__))
env_path = os.path.join(root, '.env')

print('This helper will create a `.env` file in the project root.')
print('Do NOT paste real production secrets if you do not want them stored locally.')

admin = input('Enter ADMIN_API_KEYS (comma separated): ').strip()
users = input('Enter USER_API_KEYS (comma separated): ').strip()
redis_url = input('Enter REDIS_URL (e.g. redis://localhost:6379/0) [leave empty for none]: ').strip()
paypal_user = input('Enter PAYPAL_USERNAME: ').strip()
paypal_pass = getpass.getpass('Enter PAYPAL_PASSWORD (input hidden): ').strip()

lines = []
if admin:
    lines.append(f'ADMIN_API_KEYS={admin}')
if users:
    lines.append(f'USER_API_KEYS={users}')
if redis_url:
    lines.append(f'REDIS_URL={redis_url}')
lines.append(f'PAYPAL_USERNAME={paypal_user}')
lines.append(f'PAYPAL_PASSWORD={paypal_pass}')

with open(env_path, 'w', encoding='utf-8') as f:
    f.write('# Generated by scripts/create_env.py - keep this file secret and out of version control\n')
    f.write('\n'.join(lines) + '\n')

print(f'Wrote {env_path}. Add it to your .gitignore if not already ignored.')
print('Done.')
